version: '2'
services:
  app:
    container_name: app.mtg-exchange
    user: www-data
    working_dir: /app
    build:
      context: ./
      dockerfile: ./.docker/build/php-fpm.dockerfile
    links:
      - db
    volumes:
      - .:/app
      - ./.docker/configs/php-fpm/www.conf:/etc/php/7.1/fpm/pool.d/www.conf
    restart: always

  cli:
    container_name: cli.mtg-exchange
    user: application
    working_dir: /app
    build:
      context: ./
      dockerfile: ./.docker/build/php-cli.dockerfile
    links:
      - db
    volumes:
      - .:/app

  composer:
      container_name: composer.mtg-exchange
      user: application
      working_dir: /app
      build:
        context: ./
        dockerfile: ./.docker/build/php-cli.dockerfile
      links:
        - db
      volumes:
        - .:/app
        - $HOME/.composer:/home/application/.composer

  nginx:
      container_name: nginx.mtg-exchange
      image: "nginx:alpine"
      ports:
        - "80:80"
      volumes:
        - ./.docker/configs/nginx/mtg-exchange.nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/app
      restart: always
      links:
        - app

  db:
    container_name: mysql.mtg-exchange
    image: "mysql:latest"
    environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_DATABASE=mtg_exchange
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql